name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Installing build dep
      run: sudo apt install bison flex libelf-dev
    - name: Running script to build minimal x86_64 os
      run: |
        git clone --recurse-submodules https://github.com/arjuncr/minimal_x86_64_os.git
        cd minimal_x86_64_os/build-script
        ./build_x86_64.sh --build-all
        ./build_x86_64.sh --create-rootfs
        ./build_x86_64.sh --create-img
